language: bash

services:
  - docker

env:
  - APP_ENV=prod

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.25.4/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose build tools

stages:
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: deploy
      script:
        - bash scripts/build.sh
        - bash scripts/deploy_alwaysdata.sh
      
