api_platform:
    title: 'doi2pmh API'
    version: '0.1'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    #allow_plain_identifiers: true
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
        pagination_enabled: false
        pagination_client_enabled: true
