security:
    password_hashers:
        App\Entity\User:
            algorithm: sodium

    providers:
        admin_user:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        api:
            pattern: ^/api/
            stateless: true
            provider: admin_user
            jwt: ~
        
        login:
            pattern: ^/authentication_token
            json_login:
                check_path: /authentication_token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        admin:
            pattern: ^/(%app_locales%)/
            form_login:
                login_path: security_login
                check_path: security_login
            custom_authenticators:
                - App\Security\CasAuthenticator
            entry_point: form_login
            logout:
                  path: security_logout
                  target: security_login

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: '^/(%app_locales%)/admin/login', roles: PUBLIC_ACCESS }
        - { path: '^/(%app_locales%)/admin', roles: [ROLE_ADMIN, IS_AUTHENTICATED_FULLY] }
        - { path: ^/authentication_token, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
