twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        navigation_menu: '@App\Services\NavigationMenuManager'
#        pages: '@App\Services\PagesHelper'
